// Generated by scripts/build.mjs from src/host.js — do not edit directly.
/**
 * dsh-inline-pastes — 宿主半边（占位）。
 *
 * 本插件的全部能力都在浏览器半边：
 *   - 接管「剪贴板里全是图片」的粘贴事件（document 捕获阶段）；
 *   - 重命名文件为 image-1.png 这类短名；
 *   - 通过官方 conversation 服务建草稿附件 + 在光标处插入官方引用胶囊；
 *   - 自绘悬浮预览卡（输入框内联胶囊 / 已发送气泡里的名字都能命中）。
 *
 * 宿主侧只需要存在一个可加载的 loader 条目：dsh-client-modules 是靠「loader 条目
 * 的包名 → package.json 的 dsh.client 声明 → exports["./client"]」这条链把浏览器
 * bundle 接进 __DSH_BOOT__ 的，所以本文件不能缺，但也不需要做任何事。
 *
 * @module dsh-inline-pastes
 */

/** 本插件不依赖任何宿主服务。 */
export const inject = []

/** 名字（loader 条目的 name 即包名，这里保留一份便于调试输出）。 */
export const name = 'dsh-inline-pastes'

/** 宿主侧无操作：能力全在客户端。 */
export function apply() {}
