/**
 * dsh-inline-pastes — 构建脚本
 *
 * 产物两个，都进 lib/：
 *   1. lib/index.js  —— 宿主半边：src/host.js 原文 + 生成头注释；
 *   2. lib/client.js —— 浏览器半边：src/client.js 原文包进
 *      `window.__ModuleLoader__.load({ id, factory })` 的经典脚本 bundle。
 *      形态与官方 client 包 / 其它第三方插件一致，id **必须**等于 package.json 的
 *      name（dsh-client-modules 按 loader 条目的包名解析注册 ID，写错会
 *      "loaded without registering"）。
 *
 * 同时把 src/styles.css 注入 src/client.js 里的 `/*__STYLES__*\/ ''` 锚点。
 *
 * 用法：node scripts/build.mjs
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const LIB = join(ROOT, 'lib')
const MANIFEST = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))
const PLUGIN_ID = MANIFEST.name
const STYLE_ANCHOR = "/*__STYLES__*/ ''"
const VERSION_ANCHOR = "/*__VERSION__*/ '0.0.0'"

/** 读一个源文件，缺失直接报错（不静默产出半个产物）。 */
function readSource(relative) {
  const file = join(ROOT, relative)
  try {
    return readFileSync(file, 'utf8')
  } catch (error) {
    throw new Error(`构建失败：读不到 ${relative}（${error.message}）`)
  }
}

const css = readSource('src/styles.css').trim()
let clientSource = readSource('src/client.js')
if (!clientSource.includes(STYLE_ANCHOR)) {
  throw new Error(`构建失败：src/client.js 里找不到样式锚点 ${STYLE_ANCHOR}`)
}
clientSource = clientSource.replace(STYLE_ANCHOR, () => JSON.stringify(css))
if (!clientSource.includes(VERSION_ANCHOR)) {
  throw new Error(`构建失败：src/client.js 里找不到版本锚点 ${VERSION_ANCHOR}`)
}
clientSource = clientSource.replace(VERSION_ANCHOR, () => JSON.stringify(MANIFEST.version))

// 浏览器半边不得有模块解析：dsh.client.inject 是空的，factory 的 require 只服务平台模块。
const requireCall = /(^|[^.\w])require\s*\(/m.exec(clientSource.replace(/^\s*\/\*[\s\S]*?\*\/\s*/m, ''))
if (requireCall !== null) {
  throw new Error('构建失败：src/client.js 里出现了 require() 调用；本插件不依赖平台模块，请去掉它')
}

const wrapped = [
  '// Generated by scripts/build.mjs from src/client.js + src/styles.css — do not edit directly.',
  `window.__ModuleLoader__.load({ id: ${JSON.stringify(PLUGIN_ID)}, factory: (require) => {`,
  "'use strict';",
  'var module = { exports: {} }; var exports = module.exports;',
  clientSource,
  'return module.exports;',
  '} });',
  '',
].join('\n')

const hostSource = [
  '// Generated by scripts/build.mjs from src/host.js — do not edit directly.',
  readSource('src/host.js').trim(),
  '',
].join('\n')

rmSync(LIB, { recursive: true, force: true })
mkdirSync(LIB, { recursive: true })
writeFileSync(join(LIB, 'index.js'), hostSource)
writeFileSync(join(LIB, 'client.js'), wrapped)

/* ---- 产物自检：形态错了就别让脏产物落地 ---- */
const problems = []
if (!wrapped.includes(`window.__ModuleLoader__.load({ id: ${JSON.stringify(PLUGIN_ID)}`)) problems.push('bundle id 与包名不一致')
if (!wrapped.includes('return module.exports;')) problems.push('bundle 缺少 module.exports 返回')
if (!wrapped.includes(`data-dsh-inline-pastes`)) problems.push('样式没有注入（锚点替换失败）')
if (!wrapped.includes(`const VERSION = ${JSON.stringify(MANIFEST.version)}`)) problems.push('版本号没有注入（锚点替换失败）')
if (!wrapped.includes(`'${PLUGIN_ID}'`) && !wrapped.includes(`"${PLUGIN_ID}"`)) problems.push('host/loader 名字不一致')
if (problems.length > 0) {
  throw new Error(`构建产物自检失败：\n  - ${problems.join('\n  - ')}`)
}

const clientBytes = Buffer.byteLength(wrapped)
console.log(`build OK → lib/index.js（宿主占位）、lib/client.js（${(clientBytes / 1024).toFixed(1)} KB, id=${PLUGIN_ID}）`)
